import { hasUncaughtExceptionCaptureCallback } from "process"

describe('Tests', () => {
  it('Should return 1 + 1 = 2', () => {
    
  })
})